#MULTIPLICATION TABLE OF AN ENTIRE NUMBER
n = int(input('Type a number'))
mt1 = '{}x1 = {}'.format(n, n*1)
mt2 = '{}x2 = {}'.format(n, n*2)
mt3 = '{}x3 = {}' .format(n, n*3)
mt4 = '{}x4 = {}' .format(n, n*4)
mt5 = '{}x5 = {}' .format(n,n*5)
mt6 = '{}x6 = {}' .format(n, n*6)
mt7 = '{}x7 = {}' .format(n, n*7)
mt8 = '{}x8 = {}' .format(n, n*8)
mt9 = '{}x9 = {}' .format(n, n*9)
mt10 = '{}x10 = {}' .format(n, n*10)
print('-'*10)
print(mt1)
print(mt2)
print(mt3)
print(mt4)
print(mt5)
print(mt6)
print(mt7)
print(mt8)
print(mt9)
print(mt10)
print('-'*10)


